# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: Madlab

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: HCL AppScan Enterprise@2
  inputs:
    ServiceEndPointAse: 'ASE_Kripa_Joy'
    jobName: 'AzureYamlTestJoy'
    folderId: 6
    templateId: 13
    testPolicyId: 7
    loginMethod: 'None'
    startingURL: 'http://10.115.153.71:18080/WebGoat/login'
    optimization: Fastest
